### ISSUE TITLE
How could you convert pytorch model to keras

### ISSUE THREAD

**Issue by shuguohe** [harish2704/pottan-ocr#13]
@harish2704 I can not convert pytorch lstmcell to keras, Could you please provide some help?
Here is pytorch lstmcell, 
self.att_lstm = nn.LSTMCell(1536,512) 
h_att, c_att = self.att_lstm(att_lstm_input, (state[0][0], state[1][0]))
state[0][0], state[1][0] is the tensor(2, 512)

**Comment by harish2704** [comment]
@shuguohe  Pytorch => Keras conversion was done manually using hand-crafted python script.
This script you can see @ https://github.com/harish2704/pottan-ocr/blob/master/tools/torch_to_keras.py 

As you can see, it is written specifically for this project, but you can see many reusable functions in that file. 
The basic logic behind the conversion is this https://github.com/harish2704/pottan-ocr/blob/c698f40b71bc9e0288205d65b7a5421120c03025/tools/torch_to_keras.py#L68

You can also see my SF question and its answer @ https://stackoverflow.com/questions/48361376/converting-state-parameters-of-pytorch-lstm-to-keras-lstm

**Comment by shuguohe** [comment]
@harish2704 not sure if you have the email address, I am not familiar with pytorch and keras, if I have some questions, maybe I can ask you. Thanks.

**Comment by shuguohe** [comment]
@harish2704 Get another issue when trying to do predict, File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 76, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'Tensor' object has no attribute 'ndim'

**Comment by harish2704** [comment]
I would suggest to use python3 for the development of this project
