### ISSUE TITLE
### Add documentation & installation instructions

### ISSUE THREAD

**Issue by harish2704** [harish2704/pottan-ocr#5]

**Comment by nithyadurai87** [comment]
Add cmake as required software for training.
add CUDA installation instructions.

**Comment by harish2704** [comment]
@nithyadurai87 : You are welcome to add documentation related to CUDA installation.
I personally do not own a Nvidia GPU , and thus haven't done that part manually. Cloud GPU providers usually provides a ready to use CUDA enabled container .
